# .github/workflows/compile-backend.yml
name: Compile Backend

on:
  push:
    paths:
      - "pom.xml"
      - "src/**"
      - ".github/workflows/compile-backend.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Compile
        run: ./mvnw -B -q -DskipTests clean compile
      - name: Test
        run: ./mvnw -B -q test
